### ISSUE TITLE
Não uso o docker e comprei o curso...dinheiro fora?

### ISSUE THREAD

**Issue by luxu** [evolutio/djavue#2]
Pq td se faz com docker e não gosto do docker..

**Comment by huogerac** [comment]
hey cara, entendo que é frustante no começo, mas docker já é uma tecnologia aceita e cedo ou tarde teremos que estudar!

Enfim, uma dica é se quiser montar um projeto sem docker e ele tem um Dockerfile, é como ter todas as dependencias em ordem para instalar

É só seguir fazendo os passos no seu terminal e no final tem seu projeto sem docker!

**Comment by tonylampada** [comment]
Show Roger, expliquei exatamente isso por telefone pro Luciano. Em breve teremos mais um fã de docker.
O que acontece é que a primeira experiência com docker no windows realmente pode ser traumática.

Mas dá pra mexer com o djavue tranquilamente sem docker. E pra aprender o docker, o Luciano já tem uma VM ubuntu que dá pra brincar. É exatamente o que eu recomendo pra usuarios de windows.
Avancem no curso sem docker, mas instalem uma VM ubuntu pra aprender a mexer com docker também.
